# Generated by Django 4.1 on 2022-08-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_suscriptores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='suscriptores',
            name='correo',
            field=models.EmailField(max_length=80),
        ),
        migrations.AlterField(
            model_name='suscriptores',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
